### 결제 타입 등록
POST http://localhost:8080/api/payments/charges
Content-Type: application/json

{
  "name": "토스결제"
}

### 결제 타입 수정
PUT http://localhost:8080/api/payments/charges/1
Content-Type: application/json

{
  "name": "결제"
}

### 해당 아이디에 대한 결제 타입 조회
GET http://localhost:8080/api/payments/charges/1

### 모든 결제 타입 조회
GET http://localhost:8080/api/payments/charges/

### 해당 아이디에 대한 결제 타입 삭제
DELETE http://localhost:8080/api/payments/charges/1
